### ISSUE TITLE
As a user, I'd like a notification when CI results/Checks are ready

### ISSUE THREAD

**Issue by ashanbrown** [pullreminders/backlog#81] opened 2018-10-30 03:16 UTC
When CI results come in, positive or negative, there are actions I can take immediately.  For CI successes, I want to know the status of a PR review, so I can know to merge my PR.  For CI failures, I want to know what failed immediately so I can make changes and push up a fix.

Fwiw, while we use CircleCI, we don't use CircleCI Checks.  We also use Code Climate, which is another result that could be immediately actionable.

**Comment by abinoda** [comment] 2018-10-31 23:23
👍 Adding to backlog

**Comment by abinoda** [comment] 2018-11-02 06:18
@ashanbrown My bad, realized this is a dupe of https://github.com/pullreminders/backlog/issues/69 so I'm merging this one into that one. This is coming soon!

**Closed as completed by abinoda** 2018-11-02 06:18 UTC

**Comment by sleepylemur** [comment] 2020-01-02 16:38
@abinoda looks like failure case got handled in #69 but also being notified on ci success would be sweet.
