### ISSUE TITLE
Setting reactions on a PR should not change the user/team on which a PR is waiting

### ISSUE THREAD

**Issue by terminalmage** [pullreminders/backlog#55] opened 2018-06-28 00:31 UTC
This happens pretty frequently:

1. I open a PR.
2. There is discussion, I push changes.
3. I comment on the PR thread regarding the changes I just pushed.
4. Someone adds a :+1: reaction to my comment.
5. Next time the pull reminders are sent out, my PR is marked as "waiting on @terminalmage", despite there being literally nothing for me to do.

**Comment by abinoda** [comment] 2018-06-28 00:38
@terminalmage Do you by any chance have a screenshot of this you could share just so I can confirm what is happening? Or could you confirm that the sequence below?

1. You open a PR **and assign reviewers**
2. The reminders are marked as "waiting on @review-name"
2. The reviewers review the PR and request changes
3. You push changes and leave comments, others leave reactions (e.g. 👍)
4. The reminders are marked as "waiting on @terminalmage"

You said "despite there being literally nothing for me to do" – what do you mean by that? If they thumb-supped your comments doesn't that mean you're good to proceed and/or merge?

**Comment by abinoda** [comment] 2018-06-28 00:44
While I'm waiting for your response... I'm 90% sure that this is happening to you because you are not requesting new reviews after you've pushed up changes and responded to comments. Once a PR has been reviewed, it is going to be marked as "waiting on the author" unless it is merged or reviewers are re-assigned.

I've recently updated the Pull Reminders UI to try to explain this better:
<img width="585" alt="screen shot 2018-06-27 at 8 37 11 pm" src="https://user-images.githubusercontent.com/50083/42006828-3e08232e-7a4a-11e8-90d3-b6dc9e5dcd76.png">

You can also disable the "remind author" settings if it's annoying to work around based on your workflow.

I've also written about how GitHub's UX is really not supportive of having a consistent workflow:
* https://platform.github.community/t/github-review-request-ux-leading-to-less-consistent-platform-to-build-upon/6255?u=abinoda
* https://github.com/pullreminders/backlog/issues/48

**Comment by abinoda** [comment] 2018-11-05 23:42
Closing due to inactivity. @terminalmage see my responses above

**Closed by abinoda** 2018-11-05 23:42 UTC
