### ISSUE TITLE
As a PR reviewer, I'd like to see DMs updated with the review status

### ISSUE THREAD

**Issue by ashanbrown** [pullreminders/backlog#118] opened 2019-01-31 01:44 UTC
I went to #pull-reminders in slack and saw that I had received a PR review request.  I opened it and it had already been reviewed and merged.  It would be cool if the DM could be updated with the review status and whether it has been merged.  It could be done with just a checkmark icon next to it, and whatever github uses to note merged PRs.  Someone else had commented that they'd like to see whether a PR has passed CI.  This is also potentially something that could be annotated later on a DM.

**Comment by abinoda** [comment] 2019-01-31 01:46
I think this is a dupe of https://github.com/pullreminders/backlog/issues/73. Let's move the discussion there but I have been suggesting using the `/pullreminders` command as a way to get an up-to-date list before doing work.

**Closed as completed by abinoda** 2019-01-31 01:46 UTC
